-- +migrate Up
ALTER TABLE `users` ADD COLUMN `gender` ENUM('MALE', 'FEMALE', 'OTHER') NOT NULL DEFAULT 'OTHER' COMMENT '性別' AFTER `id`;
ALTER TABLE `users` MODIFY COLUMN `gender` ENUM('MALE', 'FEMALE', 'OTHER') NOT NULL COMMENT '性別';
