// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/Goryudyuma/techblog-go-mysql-tools/internal/infra/mysql/modelutil"

const TableNameItem = "items"

// Item mapped from table <items>
type Item struct {
	ID string `db:"id"` // itemID
}

func (m *Item) ListDBTagString() []string {
	return modelutil.ListDBTagString(m)
}

// TableName Item's table name
func (*Item) TableName() string {
	return TableNameItem
}
