// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/Goryudyuma/techblog-go-mysql-tools/internal/infra/mysql/modelutil"
	"github.com/Goryudyuma/techblog-go-mysql-tools/pkg/publicType"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID     string            `db:"id"`     // ユーザーID
	Gender publicType.Gender `db:"gender"` // 性別
}

func (m *User) ListDBTagString() []string {
	return modelutil.ListDBTagString(m)
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
